### ISSUE TITLE
Error during initial-data

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-manage-service#62] opened 2021-08-17 14:20 UTC
running `./openslides initial-data`
throws:

`Error: setting initial data: setting initial data: rpc error: code = Unknown desc = parsing initial data: unmarshaling JSON: json: cannot unmarshal number into Go value of type map[string]map[string]json.RawMessage`

**Comment by normanjaeckel** [comment] 2021-09-01 09:38
Is this still valid? I worked on #65 and did not get such an error.

**Comment by tsiegleauq** [comment] 2021-09-07 10:24
yes. this is still valid. @gsiv just reproduces it aswell.

```
mkdir test
cd test
wget https://github.com/OpenSlides/openslides-manage-service/releases/download/latest/openslides
chmod +x openslides
./openslides setup .
docker-compose up --detach
./openslides initial-data
```
will throw 

```Error: setting initial data: setting initial data: rpc error: code = Unknown desc = parsing initial data: unmarshaling JSON: json: cannot unmarshal number into Go value of type map[string]map[string]json.RawMessage```

**Comment by gsiv** [comment] 2021-09-07 13:08
> yes. this is still valid. @gsiv just reproduced it as well.

At least in my case the cause appears to have a been a mismatch between the executable and the image version.  The latter needed to be updated explicitly (`docker pull`).

**Comment by tsiegleauq** [comment] 2021-09-08 11:10
`docker-compose pull`
seemd to solve at least something. This should be documented.

However, `./openslides initial-data` still throws errors:

```
Error: setting initial data: setting initial data: rpc error: code = Unknown desc = inserting initial data into datastore: creating datastore object "user/1": sending write request to datastore: got response `500 INTERNAL SERVER ERROR`: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p><img src="https://http.cat/500"></img></p>
```

I suppose this comes from the datastore?

**Comment by ostcar** [comment] 2021-09-08 11:40
> I suppose this comes from the datastore?
I think so. Could you look at the logs from the datastore? It seems to be an bug in the datastore. Even when the manage-service is buggy, the datastore-service should not return a 500er.

**Comment by normanjaeckel** [comment] 2021-09-23 17:47
Should be fixed new.

**Closed by normanjaeckel** 2021-09-23 17:47 UTC
Labels: bug, management
